USE project_klbf
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Customer](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar] (500) NOT NULL,
	[Address] [varchar] (500) NOT NULL,
	[LogoURL] [varchar] (500) NOT NULL,
 CONSTRAINT [PK_Customer_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
